/**
 * Generates supabase/seed.sql from the DEMO fixtures, so a local Supabase can be
 * populated with the same clearly-fake data the app uses without a database.
 *
 *   npm run db:seed-sql
 *
 * The seed leaves `site_settings.allow_demo = false`: demo rows stay invisible to the
 * public API until you flip that flag on a local/preview project.
 */
import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import { buildFixtures } from "../src/lib/data/fixtures";

const uuid = (key: string) => {
  const h = createHash("sha1").update(`navratri-ncr:${key}`).digest("hex");
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-4${h.slice(13, 16)}-a${h.slice(17, 20)}-${h.slice(20, 32)}`;
};
const q = (v: unknown): string => {
  if (v === null || v === undefined) return "null";
  if (typeof v === "boolean") return v ? "true" : "false";
  if (typeof v === "number") return String(v);
  if (Array.isArray(v)) return `array[${v.map(q).join(", ")}]`;
  return `'${String(v).replace(/'/g, "''")}'`;
};
const arr = (v: string[], type: string) => (v.length ? `${q(v)}::public.${type}[]` : `'{}'::public.${type}[]`);

const events = buildFixtures();
const out: string[] = [
  "-- GENERATED by scripts/seed-sql.ts — DEMO fixtures only. Every title starts with “DEMO —”.",
  "-- Public visibility is still gated by site_settings.allow_demo (false by default).",
  "begin;",
];

for (const e of events) {
  const eventId = uuid(e.id);
  const venueId = uuid(`${e.id}-venue`);
  out.push(`\n-- ${e.title}`);
  out.push(
    `insert into public.venues (id, name, address, locality, area) values (${q(venueId)}, ${q(e.venue.name)}, ${q(e.venue.address)}, ${q(e.venue.locality)}, ${q(e.venue.area)}) on conflict (name, locality, area) do nothing;`,
  );
  out.push(
    `insert into public.events (id, slug, title, status, is_demo, tagline, description, types, music, organizer_name, organizer_url, venue_id, price_status, price_min_inr, price_max_inr, price_note, entry_couples_only, entry_groups_allowed, entry_stags_allowed, entry_families_welcome, entry_min_age, entry_dress_code, entry_note, food_available, food_vegetarian_only, food_note, booking_url, booking_platform, booking_verified, verified_date, verified_price, verified_entry, last_checked_at, featured, scale, published_at) values (` +
      [
        q(eventId),
        q(e.slug),
        q(e.title),
        q(e.status),
        "true",
        q(e.tagline),
        q(e.description),
        arr(e.types, "event_type"),
        arr(e.music, "music_style"),
        q(e.organizer?.name),
        q(e.organizer?.url),
        `(select id from public.venues where name = ${q(e.venue.name)} and locality = ${q(e.venue.locality)} and area = ${q(e.venue.area)})`,
        q(e.price.status),
        q(e.price.minInr),
        q(e.price.maxInr),
        q(e.price.note),
        q(e.entry.couplesOnly),
        q(e.entry.groupsAllowed),
        q(e.entry.stagsAllowed),
        q(e.entry.familiesWelcome),
        q(e.entry.minAge),
        q(e.entry.dressCode),
        q(e.entry.note),
        q(e.food.available),
        q(e.food.vegetarianOnly),
        q(e.food.note),
        q(e.booking?.url),
        q(e.booking?.platform),
        q(e.booking?.verified ?? false),
        q(e.verification.dateChecked),
        q(e.verification.priceChecked),
        q(e.verification.entryChecked),
        q(e.verification.lastCheckedAt),
        q(e.featured),
        q(e.scale),
        "now()",
      ].join(", ") +
      `) on conflict (slug) do nothing;`,
  );
  for (const o of e.occurrences)
    out.push(`insert into public.event_occurrences (event_id, date, start_time, end_time, note) values (${q(eventId)}, ${q(o.date)}, ${q(o.startTime)}, ${q(o.endTime)}, ${q(o.note)}) on conflict do nothing;`);
  for (const s of e.sources)
    out.push(`insert into public.event_sources (id, event_id, kind, label, url, checked_at) values (${q(uuid(s.id))}, ${q(eventId)}, ${q(s.kind)}, ${q(s.label)}, ${q(s.url)}, ${q(s.checkedAt)}) on conflict do nothing;`);
  for (const v of e.vibes)
    out.push(`insert into public.event_vibes (event_id, tag, evidence, source_id) values (${q(eventId)}, ${q(v.tag)}, ${q(v.evidence)}, ${q(v.sourceId ? uuid(v.sourceId) : null)}) on conflict do nothing;`);
  if (e.crowd) {
    // Approved reports spread inside the range, so crowd_summary reproduces the same low–high band.
    const { womenPctLow: lo, womenPctHigh: hi, reportCount: n } = e.crowd;
    for (let i = 0; i < n; i++) {
      const est = Math.round(lo + 1 + ((hi - lo - 2) * i) / Math.max(1, n - 1));
      out.push(`insert into public.crowd_reports (event_id, edition_year, women_pct_estimate, status) values (${q(eventId)}, 2025, ${est}, 'approved');`);
    }
  }
}
out.push("\ncommit;");
writeFileSync("supabase/seed.sql", out.join("\n") + "\n");
console.log(`Wrote supabase/seed.sql with ${events.length} DEMO events.`);
